# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4ad584f6a19c7e5b057d73f9ffb04c93513fe69b6fec71044f011800873114de6f0e75de6da086f32a9c9d1adf61a9ccdb47b3805779a25b9f334d960c3b6ef

test:
  secret_key_base: 7ff2d7bd17bb5e223aa008cb595c90bdc31693cebd96b7a0bd58240e120885dba2abff1829437f29f304bd82169639fd93b12c95791a46985029951c0b196709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
